//
//  NFStyleKit.h
//  Nesia
//
//  Created by Alex on 5/23/17.
//  Copyright © 2017 Gemicle. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>

#define UIColorFromRGB(rgbValue) \
[UIColor colorWithRed:((float)((rgbValue & 0xFF0000) >> 16))/255.0 \
green:((float)((rgbValue & 0x00FF00) >>  8))/255.0 \
blue:((float)((rgbValue & 0x0000FF) >>  0))/255.0 \
alpha:1.0]

@interface NFStyleKit : NSObject

// Colors
+ (UIColor*)bASE_GREEN;
+ (UIColor*)lIGHT_GREEN;
+ (UIColor*)sUPER_LIGHT_GREEN;
+ (UIColor*)_base_GREY;
+ (UIColor*)_borderDarkGrey;
+ (UIColor*)_lightGrey;
+ (UIColor*) _googleRed;
+ (UIColor*) _PLACEHOLDER_STANDART_COLOR;

+ (UIColor *)colorFromHexString:(NSString *)hexString;

// Drawing Methods
+ (void)drawRoundetViewWithFrame: (CGRect)frame;
+ (void)drawCircleWithFrame: (CGRect)frame;
+ (void)drawLogoCircleWithFrame: (CGRect)frame;
+ (void)drawLeftRoundButtonWithFrame: (CGRect)frame;

+ (void)drawDownBorderWithView: (UIView* )view;
+ (void)drawDownBorderWithView: (UIView* )view withOffset:(CGFloat)offset;
+ (UIView*)returnDownBorderWithView:(UIView* )view withOffset:(CGFloat)offset;
+ (void)drawTopBorderWithView: (UIView* )view withOffset:(CGFloat)offset;
+ (void)foterViewWithAddTextFieldtoTableView:(UITableView*)tableView withTarget:(id)target;


// Generated Images
+ (UIImage*)imageOfRoundetViewWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfCircleWithSize: (CGSize)imageSize;

+ (UIImage*)imageOfCirclePointWithSize: (CGSize)imageSize;

@end
