//
//  NFStyleKit.h
//  Nesia
//
//  Created by Alex on 5/23/17.
//  Copyright © 2017 Gemicle. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>


@interface NFStyleKit : NSObject

// Colors
+ (UIColor*)bASE_GREEN;
+ (UIColor*)lIGHT_GREEN;
+ (UIColor*)sUPER_LIGHT_GREEN;
+ (UIColor*)_base_GREY;
+ (UIColor*)_borderDarkGrey;
+ (UIColor*)_lightGrey;
+ (UIColor*) _googleRed;

// Drawing Methods
+ (void)drawRoundetViewWithFrame: (CGRect)frame;
+ (void)drawCircleWithFrame: (CGRect)frame;
+ (void)drawLogoCircleWithFrame: (CGRect)frame;
+ (void)drawLeftRoundButtonWithFrame: (CGRect)frame;

+ (void)drawDownBorderWithView: (UIView* )view;
+ (void)drawDownBorderWithView: (UIView* )view withOffset:(CGFloat)offset;
+ (UIView*)returnDownBorderWithView:(UIView* )view withOffset:(CGFloat)offset;
+ (void)drawTopBorderWithView: (UIView* )view withOffset:(CGFloat)offset;
+ (void)foterViewWithAddTextFieldtoTableView:(UITableView*)tableView withTarget:(id)target;


// Generated Images
+ (UIImage*)imageOfRoundetViewWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfCircleWithSize: (CGSize)imageSize;

@end
